### ISSUE TITLE
TypeError: Object object has no method 'hasOwnProperty'

### ISSUE THREAD

**Issue by ezeq-10** [albin3/express-redis-session#1]
Hi, 
First of all, thanks for this great library, i have a little problem when deleted the cookies from the browser:

I've installed the node-redis-session dependency and in the first time runs fine, but i've deleted the created cookies of the browser, and now I cannot make it run again.

This is the error message

TypeError: Object object has no method 'hasOwnProperty'
at ~/../server/node_modules/node-redis-session/lib/index.js:57:22
And this is an extract of the code (line 57)

var sid;
if (!req.cookies.hasOwnProperty(cookieName)) {
  //easy to find in redis with command "keys \* s|*"
  sid = 's|'+generateSid();
  req.cookies[cookieName] = sid;
  res.cookie(cookieName, sid, { expires: new Date(new Date().getTime()+expireTime), httpOnly: true });
}

**Comment by albin3** [comment]
published @0.2.5 🍺
